table Giacenze
	lineageTag: 9b928d17-3c09-44d0-a857-37b4756607ec

	column legal_entity
		dataType: string
		lineageTag: 9d733baf-8b61-4d92-abb9-e903899ada7f
		summarizeBy: none
		sourceColumn: legal_entity

		annotation SummarizationSetBy = Automatic

	column item_code
		dataType: string
		lineageTag: 2da3e27c-a820-4016-8dbc-1cf0ecea2b35
		summarizeBy: none
		sourceColumn: item_code

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76582765-910d-4066-83ce-59f3209cadb0
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 9cff5463-1148-4386-81f6-f695bf013b14
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	partition Giacenze = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(REPO_ROOT & "\data\stock.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"legal_entity", type text}, {"item_code", type text}, {"date", type date}, {"quantity", Int64.Type}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

